config/routes.rb
Rails.application.routes.draw do
  resources :roles
  resources :roles
  resources :roles
  resources :roles

end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestTheme</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/roles/_form.html.slim
= form_for @role do |f|
  - if @role.errors.any?
    #error_explanation
      h2 = "#{pluralize(@role.errors.count, "error")} prohibited this role from being saved:"
      ul
        - @role.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .actions = f.submit

app/views/roles/edit.html.slim
h1 Editing role

== render 'form'

= link_to 'Show', @role
'|
= link_to 'Back', roles_path

app/views/roles/index.html.slim
h1 Listing roles

table
  thead
    tr
      th Name
      th
      th
      th

  tbody
    - @roles.each do |role|
      tr
        td = role.name
        td = link_to 'Show', role
        td = link_to 'Edit', edit_role_path(role)
        td = link_to 'Destroy', role, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Role', new_role_path

app/views/roles/new.html.slim
h1 New role

== render 'form'

= link_to 'Back', roles_path

app/views/roles/show.html.slim
p#notice = notice

p
  strong Name:
  = @role.name

= link_to 'Edit', edit_role_path(@role)
'|
= link_to 'Back', roles_path